#general
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
GRAVITY_CONSTANT = 3
#player
X_SPEED_FALL = 10
JUMP_X_BOOST_K = 2
PLAYER_JUMP_COYOTE_TIME = 0.1
MAX_JUMPS = 1
PLAYER_JUMP_BUFFER = 0.1
PLAYER_MAX_HP = 100
PLAYER_JUMP_SPEED = 20
PLAYER_SPRINT_K = 2
PLAYER_MAX_ENERGY = 100
PLAYER_ENERGY_RECOVERY_SPEED = 15
PLAYER_SPRINT_COST = 20 #per second
PLAYER_JUMP_TIMEOUT = 1
PLAYER_JUMP_COST = 36 #per turn
PLAYER_WALK_SPEED = 100
PLAYER_CLIMB_SPEED = 20
PLAYER_INVENTORY_SIZE = 4
#standart zombie
STANDART_ZOMBIE_HP = 50
#weapons
BULLET_TEXTURE = "assets/Weapons/pistol_bullet.png"
WEAPON_RECOIL_FALL_SPEED = 50
#Melee
MELEE_DAMAGE = 10
#Machete
MACHETE_DAMAGE = 20
BULLET_STEP = 2
BULLET_MAX_STEPS = 1000
BULLET_SMOKE_PARTICLE_MAX_SPEED_X = 0.1
BULLET_SMOKE_PARTICLE_LIFETIME = 3
BULLET_SMOKE_PARTICLE_SPEED_Y = 10
BULLET_SMOKE_PARTICLES_COUNT = 100
BULLET_SMOKE_PARTICLE_TEXTURE = "assets/bullet_smoke_particle.png"
#Pistol
PISTOL_TEXTURE = "assets/Weapons/pistol.png"
PISTOL_BULLET_TEXTURE = BULLET_TEXTURE
PISTOL_SCALE = 0.6
PISTOL_MAX_AMMO = 17
PISTOL_RECHARGING_SPEED = 0.4
PISTOL_STRIKE_SPEED = 1.4
PISTOL_BULLET_START_Y_FROM_BOTTOM = 23.5
PISTOL_RECOIL_PER_STRIKE = 10
PISTOL_BULLET_DAMAGE = 20
PISTOL_BULLET_SCALE = 0.3
PISTOL_BULLET_FALL_SPEED = 0.000002
PISTOL_BULLET_MAX_STEPS = BULLET_MAX_STEPS
PISTOL_SETUP = (PISTOL_TEXTURE, PISTOL_SCALE, PISTOL_MAX_AMMO, PISTOL_STRIKE_SPEED, PISTOL_RECHARGING_SPEED,
                PISTOL_BULLET_START_Y_FROM_BOTTOM, PISTOL_RECOIL_PER_STRIKE, PISTOL_BULLET_TEXTURE, PISTOL_BULLET_SCALE,
                PISTOL_BULLET_DAMAGE, PISTOL_BULLET_FALL_SPEED, PISTOL_BULLET_MAX_STEPS)
#Auto pistol
AUTO_PISTOL_RECOIL_PER_STRIKE = 10
AUTO_PISTOL_MAX_AMMO = 30
#Assault Rifle
AS_RIFLE_RECOIL_PER_STRIKE = 10
AS_RIFLE_MAX_AMMO = 40
#Other items
#medicine(first aid kit)
MEDICINE_POWER = 40
#adrenaline
ADRENALINE_POWER = 100
