import random

from engine.Item import EquippableItem, Ammo
# from engine.Weapon import Ammo
# general
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
GRAVITY_CONSTANT = 3
GAME_CAMERA_LERP = 0.12
# background
BRIGHT_CONTROL_TEXTURE = "assets/Background/bright_control.png"
# database
# hud
HP_HUD_ICON_TEXTURE = "assets/HUD/hp_icon.png"
ENERGY_HUD_ICON_TEXTURE = "assets/HUD/energy_icon.png"
# player
X_SPEED_FALL = 10
JUMP_X_BOOST_K = 3
PLAYER_JUMP_COYOTE_TIME = 0.1
MAX_JUMPS = 1
PLAYER_JUMP_BUFFER = 0.1
PLAYER_MAX_HP = 100
PLAYER_JUMP_SPEED = 20
PLAYER_SPRINT_K = 2
PLAYER_MAX_ENERGY = 100
PLAYER_ENERGY_RECOVERY_SPEED = 20
PLAYER_SPRINT_COST = 0  # per second
PLAYER_JUMP_TIMEOUT = 0.4
PLAYER_JUMP_COST = 36  # per turn
PLAYER_WALK_SPEED = 100
PLAYER_CLIMB_SPEED = 20
# inventory
PLAYER_INVENTORY_SIZE = 6
PLAYER_INVENTORY_TEXTURE = ""
PLAYER_INVENTORY_WIDTH = PLAYER_INVENTORY_HEIGHT = 80
# animation
PLAYER_WALKING_TEXTURE = "assets/Player/walk/player_walking_no_hands.png"
# zombie
STANDART_ZOMBIE_HP = 50
ZOMBIE_TEXTURE = "assets/TileMaps/Zombie.png"
# Inventory
INVENTORY_SLOT_SIZE = 80
INVENTORY_SLOT_TEXTURE = "assets/Inventory/inventory_slot.png"
INVENTORY_SLOT_FORBIDDEN_TEXTURE = "assets/Inventory/inventory_slot_on_forbidden.png"
INVENTORY_SLOT_ON_CHOICE_TEXTURE = "assets/Inventory/inventory_slot_on_choice.png"
INVENTORY_SLOT_FOR_DROPPING_TEXTURE = "assets/Inventory/slot_for_dropping.png"
INVENTORY_SLOT_TEXTURE_OUTLINE = 5
INVENTORY_EQUIPMENT_FOR_HEAD_SLOT_TEXTURE = HEAD = "assets/Inventory/equipment_head_slot.png"
INVENTORY_EQUIPMENT_FOR_BODY_SLOT_TEXTURE = BODY = "assets/Inventory/equipment_body_slot.png"
INVENTORY_EQUIPMENT_SLOTS = (
    (EquippableItem.FOR_HEAD, HEAD, -3, 45), (EquippableItem.FOR_BODY, BODY, -3, 10))
PLAYER_TEXTURE_NO_HANDS = "assets/Player/idle/default_idle_no_hands.png"
PLAYER_HAND_TEXTURE = "assets/Player/player_hand.png"
# standart zombie
STANDARD_ZOMBIE_HP = 50
# weapons
WEAPON_MODIFICATIONS_POS = ()
BULLET_TEXTURE = "assets/Weapons/pistol_bullet.png"
WEAPON_RECOIL_FALL_SPEED = 50
BULLET_STEP = 2
BULLET_MAX_STEPS = 1000
BULLET_SMOKE_PARTICLE_MAX_SPEED_X = 0.1
BULLET_SMOKE_PARTICLE_LIFETIME = 3
BULLET_SMOKE_PARTICLE_SPEED_Y = 10
BULLET_SMOKE_PARTICLES_COUNT = 10
BULLET_SMOKE_PARTICLES_INTERVAL = 0.1
BULLET_SMOKE_PARTICLE_TEXTURE = "assets/bullet_smoke_particle.png"
# Weapons
WEAPONS_BARREL_END_POS_X_FROM_CENTER = (20, 50, 60)
# Pistol
PISTOL_BULLET_TEXTURE = BULLET_TEXTURE
PISTOL_MAX_AMMO = 17
PISTOL_RECHARGING_SPEED = 0.4
PISTOL_STRIKE_SPEED = 1.4
PISTOL_BULLET_START_Y_FROM_CENTER = 10
PISTOL_RECOIL_PER_STRIKE = 12
PISTOL_BULLET_DAMAGE = 10
PISTOL_BULLET_SCALE = 0.3
PISTOL_BULLET_FALL_SPEED = 0.000004
PISTOL_BULLET_MAX_STEPS = BULLET_MAX_STEPS
PISTOL_MAX_STRIKES_PER_CLICK = (1,)
PISTOL_SETUP = (PISTOL_MAX_AMMO, PISTOL_STRIKE_SPEED, PISTOL_RECHARGING_SPEED,
                PISTOL_BULLET_START_Y_FROM_CENTER, PISTOL_RECOIL_PER_STRIKE, Ammo.PISTOL_BULLET,
                PISTOL_BULLET_TEXTURE, PISTOL_BULLET_SCALE,
                PISTOL_BULLET_DAMAGE, PISTOL_BULLET_FALL_SPEED, PISTOL_BULLET_MAX_STEPS, PISTOL_MAX_STRIKES_PER_CLICK)
PISTOL_AMMO_SETUP = (25, Ammo.PISTOL_BULLET)
# Auto pistol
AUTO_PISTOL_RECOIL_PER_STRIKE = 10
AUTO_PISTOL_MAX_AMMO = 30
AUTO_PISTOL_STRIKE_SPEED = 13
AUTO_PISTOL_RECHARGING_SPEED = 0.3
AUTO_PISTOL_BULLET_START_Y_FROM_CENTER = 12
AUTO_PISTOL_BULLET_DAMAGE = 14
AUTO_PISTOL_MAX_STRIKES_PER_CLICK = (1, 2, 30)
AUTO_PISTOL_SETUP = (AUTO_PISTOL_MAX_AMMO, AUTO_PISTOL_STRIKE_SPEED, AUTO_PISTOL_RECHARGING_SPEED,
                     AUTO_PISTOL_BULLET_START_Y_FROM_CENTER, AUTO_PISTOL_RECOIL_PER_STRIKE, Ammo.PISTOL_BULLET,
                     PISTOL_BULLET_TEXTURE, PISTOL_BULLET_SCALE,
                     AUTO_PISTOL_BULLET_DAMAGE, PISTOL_BULLET_FALL_SPEED, PISTOL_BULLET_MAX_STEPS,
                     AUTO_PISTOL_MAX_STRIKES_PER_CLICK)
# Assault Rifle
AS_RIFLE_RECOIL_PER_STRIKE = 14
AS_RIFLE_MAX_AMMO = 40
AS_RIFLE_STRIKE_SPEED = 11
AS_RIFLE_RECHARGING_SPEED = 0.3
AS_RIFLE_BULLET_START_Y_FROM_CENTER = 10
AS_RIFLE_BULLET_DAMAGE = 24
AS_RIFLE_MAX_STRIKES_PER_CLICK = (1, 40)
AS_RIFLE_SETUP = (AS_RIFLE_MAX_AMMO, AS_RIFLE_STRIKE_SPEED, AS_RIFLE_RECHARGING_SPEED,
                  AS_RIFLE_BULLET_START_Y_FROM_CENTER, AS_RIFLE_RECOIL_PER_STRIKE, Ammo.RIFLE_BULLET,
                  PISTOL_BULLET_TEXTURE, PISTOL_BULLET_SCALE,
                  AS_RIFLE_BULLET_DAMAGE, PISTOL_BULLET_FALL_SPEED, PISTOL_BULLET_MAX_STEPS,
                  AS_RIFLE_MAX_STRIKES_PER_CLICK)
AS_RIFLE_AMMO_SETUP = (20, Ammo.RIFLE_BULLET)
# Other items
# medicine(first aid kit)
MEDICINE_CONNECTED_TO = ("hp",)
MEDICINE_POWER = (40,)
MEDICINE_SETUP = (MEDICINE_POWER, MEDICINE_CONNECTED_TO)
# adrenaline
ADRENALINE_POWER = (-2,)
ADRENALINE_CONNECTED_TO = ("sprint_cost",)
ADRENALINE_DURATION = 100
ADRENALINE_SETUP = (
    ADRENALINE_POWER, ADRENALINE_CONNECTED_TO, ADRENALINE_DURATION)
# pain_killer
PAIN_KILLER_POWER = (20,)
PAIN_KILLER_CONNECTED_TO = ("hp",)
PAIN_KILLER_DURATION = 120
PAIN_KILLER_SETUP = (
    PAIN_KILLER_POWER, PAIN_KILLER_CONNECTED_TO, PAIN_KILLER_DURATION)
# night_vision_googles
NIGHT_GOOGLES_POWER = (30,)
NIGHT_GOOGLES_CONNECTED_TO = ("brightness",)
NIGHT_GOOGLES_EQUIP_PLACE = EquippableItem.FOR_HEAD
NIGHT_GOOGLES_SETUP = (NIGHT_GOOGLES_POWER, NIGHT_GOOGLES_CONNECTED_TO)
# armor
ARMOR_POWER = (30, -5)
ARMOR_CONNECTED_TO = ("resistance", "energy_recovery_speed")
ARMOR_EQUIP_PLACE = EquippableItem.FOR_BODY
ARMOR_SETUP = (ARMOR_POWER, ARMOR_CONNECTED_TO)
# modifications
WEAPON_MODIFICATIONS_ID = (10, 11)
# SmartLaserAim
SMART_LASER_AIM_SETUP = tuple()
# AntiRecoil
ANTI_RECOIL_POWER = (-6,)
ANTI_RECOIL_CONNECTED_TO = ("recoil_per_strike",)
ANTI_RECOIL_SETUP = (ANTI_RECOIL_POWER, ANTI_RECOIL_CONNECTED_TO)
# LongBarrel
LONG_BARREL_POWER = (5,)
LONG_BARREL_CONNECTED_TO = ("bullet.damage",)
LONG_BARREL_SETUP = (LONG_BARREL_POWER, LONG_BARREL_CONNECTED_TO)
# CampLevel
ITEM_PRICES = (100, 250, 400, 150, 100, 50, 300, 200, 20, 30, 100, 100)
TRADER_ITEMS_GEN_TUPLE = ((3,) * 4 + (4,) * 6 + (5,) * 6 + (6,) + (7,) * 2 + (8,) * 8
                          + (9,) * 6 + (None,) * 10)
TRADER_INVENTORY_SIZE = 6
TRADER_TEXTURE = "assets/NPC/trader_with_hands.png"
DOCTOR_ITEMS_GEN_TUPLE = ((3, ) + (4, ) * 2 + (5, ) * 1 + (None, ) * 1)
DOCTOR_INVENTORY_SIZE = 4
DOCTOR_TEXTURE = "assets/NPC/doctor_with_hands.png"
ARMORER_ITEMS_GEN_TUPLE = ((0,) * 4 + (1,) * 2 + (2,) + (10, ) * 2 + (11, ))
ARMORER_INVENTORY_SIZE = 3
ARMORER_TEXTURE = "assets/NPC/armorer_with_hands.png"
# LEVELS
CAMP_LEVEL = "assets/TileMaps/camp_level.json"
NULL_LEVEL = "assets/TileMaps/null_level.json"
FIRST_LEVEL = "assets/TileMaps/second_level.json"
SECOND_LEVEL = "assets/TileMaps/third_level.json"
