#general
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
GRAVITY_CONSTANT = 3
#player
X_SPEED_FALL = 30
JUMP_X_BOOST_K = 5
PLAYER_JUMP_COYOTE_TIME = 0.1
MAX_JUMPS = 1
PLAYER_JUMP_BUFFER = 0.1
PLAYER_HP = 100
PLAYER_JUMP_SPEED = 20
PLAYER_SPRINT_K = 2
PLAYER_MAX_ENERGY = 100
PLAYER_SPRINT_COST = 3 #per second
PLAYER_JUMP_COST = 36 #per turn
PLAYER_WALK_SPEED = 100
PLAYER_CLIMB_SPEED = 20
WOUNDS_SLOWING_K = 0.25
#standart zombie
STANDART_ZOMBIE_HP = 50
#weapons
RECOIL_K = 2
#Melee
MELEE_DAMAGE = 10
#Machete
MACHETE_DAMAGE = 20
#Pistol
PISTOL_MAX_AMMO = 17
#Auto pistol
AUTO_PISTOL_MAX_AMMO = 30
#Assault Rifle
AS_RIFLE_MAX_AMMO = 40
